from __future__ import annotations

from dataclasses import dataclass, field
import re
from typing import Pattern


@dataclass(frozen=True)
class TitleRule:
    rule_id: str
    pattern_text: str
    normalized_title: str
    role_family: str
    priority: int
    match_method: str = "rule_pattern"
    pattern: Pattern[str] = field(init=False, repr=False)

    def __post_init__(self) -> None:
        object.__setattr__(self, "pattern", re.compile(self.pattern_text, re.IGNORECASE))

    def matches(self, text: str) -> bool:
        return bool(self.pattern.search(text))


def get_rules() -> list[TitleRule]:
    rules = [
        TitleRule(
            "non_role_general_application",
            r"\bgeneral applications?\b",
            "non_role_recruiting_entry",
            "non_role",
            5,
            "rule_exact",
        ),
        TitleRule(
            "non_role_open_application",
            r"\bopen application\b",
            "non_role_recruiting_entry",
            "non_role",
            5,
            "rule_exact",
        ),
        TitleRule(
            "non_role_general_interest_talent_community",
            r"\bgeneral interest\b.*\btalent community\b|\btalent community\b|\btalent pool\b",
            "non_role_recruiting_entry",
            "non_role",
            5,
            "rule_pattern",
        ),
        TitleRule(
            "non_role_future_opportunity",
            r"\bfuture opportunit(?:y|ies)\b|\bfuture consideration\b",
            "non_role_recruiting_entry",
            "non_role",
            5,
            "rule_pattern",
        ),
        TitleRule(
            "non_role_expression_of_interest",
            r"\bexpression of interest\b|\bapply here\b",
            "non_role_recruiting_entry",
            "non_role",
            5,
            "rule_pattern",
        ),
        TitleRule(
            "non_role_dont_see_fit",
            r"\bdon(?:'| )?t see (?:what you(?:'| |’)re looking for|a role that fits|a position that interests you|an opportunity)\b",
            "non_role_recruiting_entry",
            "non_role",
            5,
            "rule_pattern",
        ),
        TitleRule(
            "health_nurse_practitioner",
            r"\bpsychiatric mental health nurse practitioner\b|\bpmhnp\b|\bnurse practitioner\b",
            "nurse_practitioner",
            "healthcare_clinical",
            15,
        ),
        TitleRule("health_psychiatrist", r"\bpsychiatrist\b", "psychiatrist", "healthcare_clinical", 16),
        TitleRule(
            "health_psychotherapist",
            r"\bpsychotherapists?\b",
            "psychotherapist",
            "healthcare_clinical",
            17,
        ),
        TitleRule(
            "health_behavioral_support",
            r"\bregistered behavior technician\b|\bbehavior technician\b|\bintervention specialist\b|\bdirect support professional\b|\bdsp\b",
            "behavioral_support_specialist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_registered_nurse",
            r"\bregistered nurse\b|\brn\b",
            "registered_nurse",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_licensed_practical_nurse",
            r"\blicensed practical nurse\b|\blpn\b|\blvn\b",
            "licensed_practical_nurse",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_licensed_vocational_nurse",
            r"\blicensed vocational nurse\b",
            "licensed_practical_nurse",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_clinical_research_nurse",
            r"\bclinical research nurse\b",
            "registered_nurse",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_staff_nurse",
            r"\bstaff nurse\b",
            "registered_nurse",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_medical_assistant",
            r"\bmedical assistant\b(?!\s+instructor\b)",
            "medical_assistant",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_certified_nursing_assistant",
            r"\bcertified nursing assistant\b|\bcna\b",
            "certified_nursing_assistant",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_pharmacy_technician",
            r"\bpharmacy technician\b",
            "pharmacy_technician",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_patient_care_technician",
            r"\bpatient care technician\b",
            "patient_care_technician",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_behavioral_interventionist",
            r"\bbehavioral interventionists?\b",
            "behavioral_support_specialist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_board_certified_behavior_analyst",
            r"\bboard certified behavior analyst\b|\bbcba\b",
            "behavioral_support_specialist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_behavior_analyst",
            r"\bbehavior analyst\b",
            "behavioral_support_specialist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_licensed_mental_health_therapist",
            r"\blicensed mental health therapist\b",
            "psychotherapist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_clinical_social_worker",
            r"\blicensed clinical social worker\b|\blcsw\b",
            "psychotherapist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_mental_or_clinical_therapist",
            r"\bmental health therapist\b|\bclinical therapist\b|\bprimary clinical therapist\b",
            "psychotherapist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_occupational_therapist_core_v2",
            r"\boccupational therapist\b",
            "occupational_therapist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_respiratory_therapist_core_v2",
            r"\brespiratory therapist\b",
            "respiratory_therapist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_speech_language_pathologist_core_safe_v4",
            r"\bspeech language pathologist\b",
            "speech_language_pathologist",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "health_physician",
            r"\bprimary care physician\b|\bphysician\b",
            "physician",
            "healthcare_clinical",
            18,
        ),
        TitleRule(
            "eng_manager",
            r"\bengineering manager\b|\bmanager,\s*software engineering\b|\bsoftware engineering manager\b",
            "engineering_manager",
            "software_engineering",
            19,
        ),
        TitleRule(
            "logistics_delivery_driver",
            r"\bcustomer delivery driver\b|\bdelivery drivers?\b",
            "delivery_driver",
            "logistics",
            20,
        ),
        TitleRule(
            "logistics_core_coordinator_specialist",
            r"^(?:senior|lead|staff|sr\.?)?\s*logistics (?:coordinator|specialist|associate)$|\bdispatcher\b|\btransportation administrator\b",
            "logistics_coordinator",
            "logistics",
            20,
        ),
        TitleRule(
            "logistics_warehouse_inventory_materials",
            r"^(?:seasonal\s+ft\s+)?warehouse associate\b|^warehouse operations associate$|^warehouse specialist$|^warehouse manager$|^warehouse general operator$|^warehouse technician$|^onsite warehouse support specialist$|^receiving associate$|^inventory (?:associate|specialist|lead|coordinator(?:\s+ii)?)$|^lead inventory coordinator$|^material handler(?:\s+i)?$|^materials specialist$|^material planner$|^materials technician$",
            "warehouse_associate",
            "logistics",
            20,
        ),
        TitleRule(
            "logistics_supply_chain_explicit",
            r"^supply chain specialist$|^senior supply chain specialist$|^supply chain intern$|^supply chain manager$|^global supply chain manager$|^director of supply chain$|^head of supply chain$|^staff supply chain planner$",
            "supply_chain_specialist",
            "logistics",
            20,
        ),
        TitleRule(
            "logistics_manager_explicit",
            r"^logistics manager$|^global logistics manager$|^senior director, global warehousing & material movement$|^warehouse & fleet manager(?:\s+\(.*\))?$|^manager, delivery services$|^director, delivery$",
            "logistics_manager",
            "logistics",
            20,
        ),
        TitleRule(
            "logistics_cdl_driver",
            r"\bcdl\b.*\bdrivers?\b|\bdrivers?\b.*\bcdl\b",
            "driver",
            "logistics",
            21,
        ),
        TitleRule(
            "trades_field_technician",
            r"\bheavy equipment field technician\b|\bfield technicians?\b.*\bmechanic\b",
            "field_technician",
            "skilled_trades",
            22,
        ),
        TitleRule(
            "trades_shop_mechanic",
            r"\bheavy equipment shop technician\b|\bshop technicians?\b.*\bmechanic\b",
            "mechanic",
            "skilled_trades",
            23,
        ),
        TitleRule(
            "trades_pump_power_hvac_field_technician",
            r"\bfield technician\b.*\bmechanic\b.*\b(pump|power|hvac)\b|\bfield technician\b.*\b(pump|power|hvac)\b.*\bmechanic\b",
            "field_technician",
            "skilled_trades",
            23,
        ),
        TitleRule(
            "trades_pump_power_hvac_shop_technician",
            r"\bshop technician\b.*\bmechanic\b.*\b(pump|power|hvac)\b|\bshop technician\b.*\b(pump|power|hvac)\b.*\bmechanic\b",
            "field_technician",
            "skilled_trades",
            23,
        ),
        TitleRule(
            "trades_automotive_parts_associate",
            r"\b(?:entry-level|mid-level|senior|junior)\s+automotive parts associate\b|\bautomotive parts associate\b",
            "store_associate",
            "sales",
            24,
        ),
        TitleRule(
            "trades_technician",
            r"\bfuture technicians?\b",
            "technician",
            "skilled_trades",
            24,
        ),
        TitleRule(
            "trades_car_detailer",
            r"\bcar detailer\b|\bautomotive detailer\b",
            "car_detailer",
            "skilled_trades",
            24,
        ),
        TitleRule(
            "trades_yard_technician",
            r"\byard technician\b|\blandscape technician\b",
            "technician",
            "skilled_trades",
            24,
        ),
        TitleRule(
            "compliance_manager",
            r"\baffiliate compliance manager\b|\bcompliance manager\b",
            "compliance_manager",
            "compliance_risk",
            25,
        ),
        TitleRule(
            "compliance_specialist",
            r"\baffiliate compliance specialist\b|\bcompliance specialist\b|\bcompliance analyst\b|\bcompliance associate\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_risk_analyst_specialist_explicit",
            r"\bthird party risk analyst\b|\brisk analyst(?:\s*i+)?\b|\bfraud analyst\b|\baml analyst\b|\b(?:junior\s+)?kyc(?:\s+onboarding)? analyst\b|\bregulatory response analyst\b|\bcredit risk analyst\b|\bfraud monitoring analyst\b|\baccount risk specialist\b|\bgrowth risk specialist\b|\bict risk analyst\b|\bgrc analyst\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_aml_kyc_fraud_investigator_explicit",
            r"\b(?:senior\s+)?(?:bsa\s*-\s*)?aml investigator\b|\bfraud investigator\b|\bfraud investigations manager\b|\bkyc representative\b|\bcompliance kyc specialist\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_internal_audit_explicit",
            r"\binternal audit (?:analyst|senior|manager)\b|\b(?:director,?\s*internal audit|head of internal audit|head of internal audit & sox)\b",
            "compliance_manager",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_risk_manager_director_explicit",
            r"\bcompliance officer\b|\bcompliance (?:lead|director)\b|\bhead of compliance(?:,\s*\w+)?\b|\b(?:operational|enterprise|financial|credit)?\s*risk manager\b|\bsenior director risk management\b|\bsenior risk manager\b|\bmanager,\s*financial risk\b|\bsenior technology and security risk manager\b",
            "compliance_manager",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_payroll_risk_compliance_explicit",
            r"\bpayroll\b.*\b(?:risk|compliance)\b|\b(?:risk|compliance)\b.*\bpayroll\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_product_compliance_managerial_explicit",
            r"\bmanager\s+global product compliance\b|\bsenior director\s+product compliance\b|\bhead of product compliance\b|\bsenior director\s+global compliance\b|\bdirector\s+corporate and regulatory compliance\b|\bdirector\s+compliance\b",
            "compliance_manager",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_product_compliance_specialist_explicit",
            r"\bproduct compliance (?:engineer|coordinator)\b|\btechnical compliance\b|\bassociate\s+risk\s*-\s*compliance\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_grc_core_explicit",
            r"\bsenior staff analyst\s+grc\b|\bsenior grc lead\b|\bgrc team intern\b|\bgovernance risk and compliance consultant\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_regulatory_affairs_manager_edge_v29",
            r"\b(?:senior\s+)?manager(?:\s*-\s*(?:senior\s+manager\s*-\s*)?)?\s+regulatory affairs\b|\bhead of regulatory affairs\b|\bdirector\s+regulatory affairs(?:\s+\w+)?\b|\bsenior director\s+regulatory affairs\b|\bvp\s+regulatory affairs\b|\bregulatory licensing and affairs team lead\b",
            "compliance_manager",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_regulatory_affairs_specialist_edge_v29",
            r"\bregulatory affairs analyst\b|\bsenior analyst\s+regulatory affairs\b|\bspecialist\s+i\s*-\s*ii\s+regulatory affairs\b|\bregulatory affairs advisor\b|\baffiliate services licensing specialist\s+regulatory affairs\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_internal_audit_manager_edge_v29",
            r"\b(?:senior\s+)?manager\s+internal audit\b|\bdirector(?: of)?\s+internal audit\b|\bvp\s+internal audit(?: and controls)?\b|\bvice president\s+internal audit\b|\binternal audit lead\b",
            "compliance_manager",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_onboarding_explicit_edge_v29",
            r"\bdirector\s+kyc and compliance onboarding\b|\bspecialist\s+onboarding compliance\b|\brisk strategist\s+onboarding and compliance\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_regulatory_operations_edge_v33",
            r"\b(?:senior\s+analyst\s+um\s+regulatory\s+operations|senior\s+analyst\s+regulatory\s+operations|director\s+regulatory\s+operations|regulatory\s+operations\s+lead|associate\s+director\s+regulatory\s+operations\s+and\s+intelligence|(?:vp|vice\s+president)\s+regulatory\s+affairs\s+strategy\s+labeling\s+and\s+operations)\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_onboarding_risk_context_edge_v33",
            r"\b(?:aml|kyc|cdd|risk|compliance)\b.*\bonboarding\b|\bonboarding\b.*\b(?:aml|kyc|cdd|risk|compliance)\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_governance_controls_specialist_edge_v36",
            r"\bassociate operational controls\b|\bmanager compliance execution (?:and|&)\s*enablement\b|\b(?:contract )?compliance coordinator\b|\bsenior analyst government compliance\b|\bproduct lead - compliance\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_governance_controls_manager_edge_v36",
            r"\bsenior team manager compliance\b|\bvice president compliance\b|\binternational trade compliance leader\b",
            "compliance_manager",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_grc_specialist_analyst_consultant_edge_v38",
            r"\b(?:information security|it)?\s*grc specialist\b|\bgrc security specialist\b|\bsecurity analyst\s*-\s*grc\b|\bsenior security analyst\s*-\s*grc\b|\btechnical grc expert\b|\bcloud security grc consultant\b|\brisk and compliance professional\b|\baml governance analyst\b|\bsenior analyst aml governance (?:&|and)\s*advisory\b",
            "compliance_specialist",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "compliance_grc_manager_director_edge_v38",
            r"\bmanager governance risk (?:&|and)\s*compliance\b|\bdirector(?: of)? governance(?: risk)?(?:,?\s*risk)?(?:,?\s*and)?\s*compliance(?:\s*&\s*trust)?\b|\bgrc director\b|\bgrc lead\b|\bgrc infosec manager\b|\bsenior security grc manager\b",
            "compliance_manager",
            "compliance_risk",
            26,
        ),
        TitleRule(
            "education_childcare_assistant",
            r"\b(?:preschool|infant|toddler|early childhood)\s+(?:assistant teacher|teaching assistant|aide)\b|\bassistant\s+(?:preschool|infant|toddler)\s+teacher\b",
            "assistant_teacher",
            "education",
            27,
        ),
        TitleRule("education_assistant_teacher", r"\bassistant teacher\b", "assistant_teacher", "education", 27),
        TitleRule("education_substitute_teacher", r"\bsubstitute teacher\b", "substitute_teacher", "education", 28),
        TitleRule(
            "education_childcare_teacher",
            r"\b(?:lead\s+)?(?:preschool|infant|toddler)\s+teacher\b|\blead\s+spanish\s+preschool\s+teacher\b|\blead\s+preschool\s+spanish\s+teacher\b|\bearly childhood teacher\b",
            "teacher",
            "education",
            28,
        ),
        TitleRule("education_teacher", r"\blead toddler teacher\b", "teacher", "education", 28),
        TitleRule(
            "education_grade_specific_teacher",
            r"\bk[- ]?5(?:th)?\s+grade\s+teacher\b|\b6[- ]?8(?:th)?\s+grade\s+teacher\b|\b9[- ]?12(?:th)?\s+grade\s+teacher\b|\b(?:1st|2nd|3rd|4th|5th)\s+grade\s+teacher\b|\b5[- ]?8(?:th)?\s+grade\s+ela\s+teacher\b|\btitle i teacher\b|\b(?:virtual\s+)?special education teacher\b|\bp\.?\s*e\.?\s+teacher\b",
            "teacher",
            "education",
            28,
        ),
        TitleRule(
            "education_instructional_aide_paraprofessional",
            r"\b(?:1\s*1\s+)?instructional aide\b|\bteacher aide\b|\b(?:classroom|school)\s+aide\b|\bparaprofessional\b",
            "assistant_teacher",
            "education",
            28,
        ),
        TitleRule(
            "education_school_counselor_edge",
            r"^school counselor$|^virtual school counselor(?:\s*\(.*\)|\s*-\s*sy\s*\d{2}-\d{2})?$",
            "school_counselor",
            "education",
            28,
        ),
        TitleRule(
            "education_school_administration_edge",
            r"^school director$|^school leadership$|^school office manager(?:\s*-\s*sy\s*\d{2}-\d{2})?$",
            "school_administrator",
            "education",
            28,
        ),
        TitleRule(
            "education_assistant_spanish_teacher_edge",
            r"^assistant spanish teacher$",
            "assistant_teacher",
            "education",
            28,
        ),
        TitleRule(
            "health_information_specialist",
            r"\bhealth information specialist\b",
            "health_information_specialist",
            "healthcare_clinical",
            29,
        ),
        TitleRule(
            "wealth_advisor",
            r"\bassociate wealth advisor\b|\bwealth advisor\b",
            "wealth_advisor",
            "finance",
            30,
        ),
        TitleRule(
            "retail_sales_associate",
            r"\blead store associate\b|\bretail sales associate\b|\bsales associate\b",
            "store_associate",
            "sales",
            31,
        ),
        TitleRule(
            "retail_stylist_explicit",
            r"\bstylist\b.*\bretail\b|\bretail\b.*\bstylist\b",
            "store_associate",
            "sales",
            31,
        ),
        TitleRule(
            "retail_floor_lead_explicit",
            r"\bfloor lead\b.*\bretail\b|\bretail\b.*\bfloor lead\b|\bfloor supervisor\b.*\bretail\b|\bretail\b.*\bfloor supervisor\b",
            "store_associate",
            "sales",
            31,
        ),
        TitleRule(
            "retail_store_advisor_associate",
            r"\bstore advisor\b|\blead store advisor\b|\bstore associate\b|\bretail advisor\b",
            "store_associate",
            "sales",
            31,
        ),
        TitleRule(
            "retail_store_management",
            r"\bassistant store manager\b|\bretail store manager\b|\bstore manager\b|\bretail manager\b|\bstore leader\b|\bstore director\b|\bretail assistant manager\b",
            "operations_specialist",
            "operations",
            32,
        ),
        TitleRule(
            "ops_rental_coordinator",
            r"\brental coordinator\b",
            "operations_specialist",
            "operations",
            32,
        ),
        TitleRule(
            "logistics_delivery_business_edge",
            r"^manager\s+delivery services$|^director\s+delivery$|^manager\s+delivery excellence$|^delivery excellence manager-?\s*east$",
            "logistics_manager",
            "logistics",
            32,
        ),
        TitleRule(
            "logistics_fulfillment_ops_edge",
            r"^fulfillment associate$|^retail delivery associate$|^customer vehicle delivery team$|^specialty pharmacy\s*-\s*delivery clerk$|^data center logistics specialist$|^fleet operator$|^autonomous fleet specialist$",
            "logistics_coordinator",
            "logistics",
            32,
        ),
        TitleRule(
            "logistics_fulfillment_management_edge",
            r"^area manager\s+fulfillment operations$",
            "logistics_manager",
            "logistics",
            32,
        ),
        TitleRule(
            "sales_regional_manager",
            r"\bregional sales manager\b",
            "account_manager",
            "sales",
            32,
        ),
        TitleRule(
            "eng_ai_engineer",
            r"\bsenior ai engineer\b|\bai engineer\b",
            "ml_engineer",
            "machine_learning",
            33,
        ),
        TitleRule(
            "eng_forward_deployed",
            r"\bforward deployed engineer\b",
            "software_engineer",
            "software_engineering",
            34,
        ),
        TitleRule(
            "sales_field_service_engineer",
            r"\btechnical sales and field service engineer\b",
            "sales_engineer",
            "sales",
            35,
        ),
        TitleRule(
            "finance_accounting_manager",
            r"\baccounting manager\b",
            "accountant",
            "finance",
            36,
        ),
        TitleRule(
            "sales_business_development_manager",
            r"\bbusiness development manager\b",
            "account_manager",
            "sales",
            37,
        ),
        TitleRule(
            "sales_inside_sales_representative",
            r"\binside sales representative\b|\benterprise inside sales representative\b|\binside sales representative(?:\s+\w+)?\b",
            "account_executive",
            "sales",
            37,
        ),
        TitleRule(
            "customer_service_advocate",
            r"\bcustomer service delivery advocate\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "customer_member_services_representative",
            r"\bmember services? (?:representative|advocate)\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "customer_service_frontline_representative",
            r"\bcustomer service (?:advisor|associate|specialist|executive)\b|\bcustomer service,\s*associate\b|\bclient service representative\b|\bcall center (?:representative|agent)\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "customer_support_frontline_representative",
            r"\bcustomer support (?:agent|associate|advocate)\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "customer_client_service_associate_edge_v37",
            r"\bclient service associate\b|\bclient services representative\b|\bsenior client services specialist\b|\bassociate\s*-\s*senior associate\s*-\s*client services\b|\bregistered brokerage client service associate(?:\s*-\s*(?:apac timezone|eastern timezone))?\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "customer_member_services_coordinator_edge_v37",
            r"\bmember services coordinator\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "customer_client_support_specialist_edge_v37",
            r"\bclient support specialist\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "customer_care_advisor_executive_edge_v39",
            r"\bcustomer care (?:advisor|executive)\b",
            "customer_service_specialist",
            "operations",
            38,
        ),
        TitleRule(
            "people_business_partner",
            r"\bpeople business partner\b|\bhr business partner\b|\bhrbp\b|\bhuman resources? business partner\b",
            "people_business_partner",
            "people_operations",
            38,
        ),
        TitleRule(
            "people_hr_generalist_core_safe_v4",
            r"\b(?:graduate|senior|sr\.?|lead|principal)?\s*(?:human resources|hr)\s+generalist\b",
            "hr_generalist",
            "people_operations",
            38,
        ),
        TitleRule(
            "ops_ai_trainer_specialist_family_v40",
            r"\bfreelance ai trainer project\b.*\bspecialist\b|\bspecialist\b.*\bfreelance ai trainer project\b",
            "ai_trainer_specialist",
            "operations",
            39,
        ),
        TitleRule(
            "ops_ai_trainer_non_specialist_family_v41",
            r"^(?=.*\bfreelance ai trainer project\b)(?!.*\bspecialist\b).+$",
            "ai_trainer_generalist",
            "operations",
            39,
        ),
        TitleRule(
            "content_technical_writer",
            r"^(?:senior|staff|principal|lead|sr\.?)?\s*technical writer(?:\s*(?:i|ii|iii|iv|v))?(?:\s+.*)?$",
            "technical_writer",
            "content",
            39,
        ),
        TitleRule(
            "content_story_desk_editor",
            r"^story desk editor$",
            "story_editor",
            "content",
            39,
        ),
        TitleRule(
            "content_multiskilled_journalist",
            r"\bmulti-?skilled journalist\b",
            "journalist",
            "content",
            39,
        ),
        TitleRule(
            "design_ux_researcher_core",
            r"\b(?:senior|staff|principal|sr\.?)?\s*ux researcher\b",
            "ux_researcher",
            "design",
            39,
        ),
        TitleRule(
            "design_art_director_core",
            r"\b(?:senior|digital|associate)?\s*art director\b",
            "art_director",
            "design",
            39,
        ),
        TitleRule(
            "design_creative_director_core",
            r"\b(?:executive\s+)?creative director(?:,\s*art)?\b",
            "creative_director",
            "design",
            39,
        ),
        TitleRule(
            "marketing_media_planning_edge_v32",
            r"^media manager(?:\s*\(traditional media\)|\s*-\s*social)?$|^senior media manager(?:\s*,\s*\(healthcare\))?$|^media planner(?:\s*-\s*(?:manager|senior specialist|specialist))?(?:\s*,\s*programmatic)?(?:\s+for traditional media)?(?:\s+offline)?(?:\s+\(london based\))?$|^senior media planner(?:\s*-\s*search)?$|^assistant media planner$|^integrated media planner$|^traditional media planner$|^offline media manager$|^senior offline media manager$|^media associate$|^programmatic media (?:manager|strategist|supervisor)$",
            "marketing_specialist",
            "marketing",
            39,
        ),
        TitleRule(
            "content_video_editor_core",
            r"\b(?:senior\s+)?video editor\b|\bvideographer and video editor\b|\b(?:photojournalist|photographer|lifestyle photographer)\s*-\s*editor\b",
            "story_editor",
            "content",
            39,
        ),
        TitleRule(
            "content_editorial_editors_edge_v30",
            r"^content editor$|^data science editor$|^copy editor$|^technical content editor$|^video content editor$|^executive editor$|^associate managing editor(?:\s*-\s*healthcare agency)?$|^managing editor\s+\w.*$|^senior editor editorial review$",
            "story_editor",
            "content",
            39,
        ),
        TitleRule(
            "legal_corporate_paralegal_v47",
            r"^(?:senior|sr\.?)?\s*corporate paralegal(?:\b.*)?$|^paralegal(?:\s+(?:i|ii|iii|iv|v))?\s*,?\s*corporate$|^corporate governance paralegals?(?:\s*\(.*\))?$",
            "paralegal",
            "legal",
            39,
        ),
        TitleRule(
            "content_producer_context_core",
            r"\b(?:video|content|digital|social|newscast|news|story|web|anime|gaming|localization|sports|comm)\b.*\bproducer\b|\bproducer\b.*\b(?:video|content|digital|social|newscast|news|story|web|anime|gaming|localization|sports|comm)\b",
            "content_producer",
            "content",
            39,
        ),
        TitleRule(
            "content_producer_creative_event_core",
            r"\b(?:creative|event|live experience|live event)\b.*\bproducer\b|\bproducer\b.*\b(?:creative|event|live experience|live event)\b",
            "content_producer",
            "content",
            39,
        ),
        TitleRule(
            "content_producer_senior_exec_core",
            r"^(?:executive producer|senior producer(?:\s*-\s*.*)?)$",
            "content_producer",
            "content",
            39,
        ),
        TitleRule(
            "content_producer_contextual_edge_v42",
            r"^(?=.*\bproducer\b)(?=.*\b(morning|evening|show|newscast|streaming|commercial|videographer|video|host|casting|conference|shoot|editor|game|live operations|features|central desk)\b)(?!.*\binsurance\b)(?!.*\bp&c\b)(?!.*\bsales\b).+$",
            "content_producer",
            "content",
            39,
        ),
        TitleRule(
            "sales_insurance_producer_geo_edge_v43",
            r"^(?:copy of\s+)?insurance producer\b(?:\s*[-,].*)?$",
            "account_executive",
            "sales",
            39,
        ),
        TitleRule(
            "sales_insurance_agent_geo_core_safe_v4",
            r"^(?:licensed\s+)?insurance agent\b(?:\s*[-,].*)?$",
            "account_executive",
            "sales",
            39,
        ),
        TitleRule(
            "sales_outside_sales_representative_safe_v6",
            r"\boutside sales representative\b",
            "account_executive",
            "sales",
            39,
        ),
        TitleRule(
            "sales_real_estate_agent_core_safe_v6",
            r"^(?:licensed|contract)?\s*real estate agent\b(?:\s*[-,:].*)?$",
            "account_executive",
            "sales",
            39,
        ),
        TitleRule(
            "retail_budtender_core_safe_v5",
            r"\bbudtender\b",
            "store_associate",
            "sales",
            39,
        ),
        TitleRule(
            "retail_dashmart_team_member_safe_v6",
            r"^dashmart variable schedule team member$",
            "store_associate",
            "sales",
            39,
        ),
        TitleRule(
            "finance_director_fpna_safe_v7",
            r"^director,?\s*f\s*p\s*&\s*a$|^senior director,?\s*f\s*p\s*&\s*a(?:\s*-\s*.*)?$",
            "financial_analyst",
            "finance",
            39,
        ),
        TitleRule(
            "ops_flight_attendant_breeze_safe_v7",
            r"^breeze airways flight attendant\s*-\s*(?:part|full)\s*time$",
            "flight_attendant",
            "operations",
            39,
        ),
        TitleRule(
            "it_support_specialist_core",
            r"^(?:senior|staff|principal|lead|sr\.?)?\s*technical support specialist(?:\s*(?:i|ii|iii|iv|v))?$",
            "it_support_specialist",
            "it_operations",
            39,
        ),
        TitleRule(
            "it_systems_administrator_core_v45",
            r"^(?!.*\bmanager\b)(?:senior|sr\.?|lead|principal|staff|junior|jr\.?|associate|it|linux|cloud|enterprise|business|financial|clinical)?\s*.*\bsystems?\s+administrator(?:\b|[^a-z].*)$",
            "it_support_specialist",
            "it_operations",
            39,
        ),
        TitleRule(
            "sales_solution_specialist_core",
            r"^(?:senior|staff|principal|lead|sr\.?)?\s*solution specialist$",
            "sales_engineer",
            "sales",
            39,
        ),
        TitleRule(
            "design_designer_variants_explicit",
            r"\b(?:senior|staff|principal|lead|sr\.?)?\s*(?:ux|ui|ux\s*-\s*ui|ui\s*-\s*ux|user experience|visual|graphic|web|digital|content|motion|integrated)\s+designer(?:\s*(?:i|ii|iii|iv|v))?\b",
            "product_designer",
            "design",
            39,
        ),
        TitleRule(
            "design_product_design_leadership_explicit",
            r"\b(?:director|head|manager|senior manager|senior director|vp),?\s*product design\b|\bproduct design (?:manager|lead)\b|\bsenior product design manager\b",
            "product_designer",
            "design",
            39,
        ),
        TitleRule(
            "marketing_copywriter_paid_media",
            r"\bcopywriter\b|\bcopywriting\b|\bad copywriting\b|\bpaid media\b",
            "marketing_specialist",
            "marketing",
            39,
        ),
        TitleRule(
            "sales_solution_engineer_singular",
            r"\bsolution engineer\b",
            "sales_engineer",
            "sales",
            39,
        ),
        TitleRule(
            "sales_engineer",
            r"\bsenior sales engineer\b|\bsales engineer\b|\bsolutions engineer\b",
            "sales_engineer",
            "sales",
            40,
        ),
        # Recovery pass v1: high-volume clusters currently falling into `other`.
        # Keep rules explicit and conservative to avoid broad overmatch.
        TitleRule(
            "arch_solution_architect_singular",
            r"\bsolution architect\b",
            "solutions_architect",
            "architecture",
            41,
        ),
        TitleRule(
            "sales_solution_specialist_consultant",
            r"\bsolutions consultant\b",
            "sales_engineer",
            "sales",
            42,
        ),
        TitleRule(
            "eng_systems_network_platform",
            r"\bplatform engineer\b|\binfrastructure engineer\b|\bcloud engineer\b|\blinux engineer\b",
            "software_engineer",
            "software_engineering",
            43,
        ),
        TitleRule(
            "infra_network_engineer_core",
            r"^(?:senior|staff|principal|lead|sr\.?)?\s*network engineer(?:\s*(?:i|ii|iii|iv|v))?$",
            "network_engineer",
            "it_operations",
            43,
        ),
        TitleRule(
            "infra_systems_engineer_core",
            r"^(?:senior|staff|principal|lead|sr\.?)?\s*systems engineer(?:\s*(?:i|ii|iii|iv|v))?$",
            "systems_engineer",
            "it_operations",
            43,
        ),
        TitleRule(
            "industrial_electrical_engineer",
            r"\b(?:senior|staff|principal|sr\.?)?\s*electrical engineer\b",
            "electrical_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "industrial_physical_design_engineer_v60",
            r"^(?:3d\s+|ai silicon\s+|silicon\s+|high voltage\s+|staff\s+|chiplet\s+|asic\s*-\s*soc silicon\s+)?physical design engineer(?:\s*(?:[-,:].*))?$",
            "electrical_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "industrial_mechanical_engineer",
            r"\b(?:senior|staff|principal|sr\.?|project|launch)?\s*mechanical engineer(?:\s*(?:i|ii|iii|iv|v))?\b",
            "mechanical_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "industrial_thermal_engineer_v60",
            r"^(?:senior|staff|principal|lead|sr\.?)?\s*thermal engineer(?:\s*(?:i|ii|iii|iv|v))?(?:\s*(?:[-,:].*))?$",
            "mechanical_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "industrial_fluids_engineer_v60",
            r"^(?:launch|senior launch|stage|test|senior|staff|principal|lead|sr\.?)?\s*fluids engineer(?:\s*(?:i|ii|iii|iv|v))?(?:\s*(?:[-,:].*))?$",
            "mechanical_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "industrial_manufacturing_engineer",
            r"\b(?:senior|staff|principal|sr\.?)?\s*manufacturing engineer\b",
            "manufacturing_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "industrial_production_engineer_core_v54",
            r"^(?:senior|sr\.?|staff|principal|lead)?\s*production engineer(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "manufacturing_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "industrial_fpga_engineer_core_v54",
            r"^(?:senior|sr\.?|staff|principal|lead)?\s*fpga engineer(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "electrical_engineer",
            "industrial_engineering",
            43,
        ),
        TitleRule(
            "eng_qa_quality",
            r"\bqa engineer\b|\bquality engineer\b",
            "software_engineer",
            "software_engineering",
            44,
        ),
        TitleRule(
            "eng_fullstack_and_servicenow",
            r"\bfull stack developer\b|\bservicenow developer\b|\bgtm engineer\b",
            "software_engineer",
            "software_engineering",
            45,
        ),
        TitleRule(
            "eng_leadership_titles",
            r"\bdirector of engineering\b|\bengineering team leader\b",
            "engineering_manager",
            "software_engineering",
            46,
        ),
        TitleRule(
            "eng_software_manager_variants_v58",
            r"^engineering director$|^(?:senior\s+)?manager\s+software (?:development|engineering)\b.*$",
            "engineering_manager",
            "software_engineering",
            46,
        ),
        TitleRule(
            "eng_software_development_manager_core_v54",
            r"^(?:senior|sr\.?|staff|principal|lead)?\s*software development manager(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "engineering_manager",
            "software_engineering",
            46,
        ),
        TitleRule(
            "data_quant_and_analyst_variants",
            r"\bproduct analyst\b|\brevenue operations analyst\b",
            "data_analyst",
            "data_analytics",
            47,
        ),
        TitleRule(
            "sales_account_director",
            r"\baccount director\b",
            "account_manager",
            "sales",
            48,
        ),
        TitleRule(
            "sales_management_cluster",
            r"\bsales manager(?:[_ -].+)?\b|\bterritory sales manager\b|\bregional sales director\b|\bdirector of sales\b|\bsales executive\b|\benterprise sales executive\b",
            "sales_manager",
            "sales",
            48,
        ),
        TitleRule(
            "sales_director_variants_v58",
            r"^director\s+sales(?:\s*[-:].*)?$|^sales director(?!\s+of\b)\b.*$|^director\s+enterprise sales(?:\s*[-:].*)?$|^vice president\s+sales$",
            "sales_manager",
            "sales",
            48,
        ),
        TitleRule(
            "sales_dev_and_bizdev_cluster",
            r"\bmanager(?:,|\s)\s*sales development\b|\bsales development manager\b|\bbusiness developer\b",
            "business_development_representative",
            "sales",
            49,
        ),
        TitleRule(
            "marketing_cluster",
            r"\bmanager,\s*paid social\b|\bpaid social manager\b|\bsenior brand designer\b",
            "marketing_specialist",
            "marketing",
            49,
        ),
        TitleRule(
            "finance_cluster",
            r"\bfinance manager\b|\btax manager\b|\bsenior actuarial analyst\b|\baccounts payable specialist\b",
            "financial_analyst",
            "finance",
            49,
        ),
        TitleRule(
            "operations_support_cluster",
            r"\boperations manager\b|\bmarket operations\b|\bimplementation manager\b|\bimplementation consultant\b|\bcustomer support representative\b|\bcustomer support specialist\b|\bcustomer service representative\b|\bclient service specialist\b|\bservice manager\b|\badministrative assistant\b|\brecruiting coordinator\b",
            "operations_specialist",
            "operations",
            49,
        ),
        TitleRule(
            "trades_production_technician",
            r"\bproduction technician\b",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_auto_technician_mechanic",
            r"\bentry-level auto technician\b|\bmid-level auto technician\b|\bsenior auto technician\b|\bmaster auto technician\b|\blead auto technician\b|\bbrake and tire auto technician\b|\bauto technician\b|\bauto mechanic\b|\bautomotive mechanic\b",
            "mechanic",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_maintenance_technician",
            r"\bfield service maintenance technician\b|\bindustrial maintenance technician\b|\bfacilities maintenance technician\b|\bequipment maintenance technician\b|\bmaintenance technician\b",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_auto_body_collision_technician",
            r"\b(?:entry[- ]level|mid[- ]level|experienced|senior|master|lead)?\s*auto body (?:repair technician|repair tech|technician)\b|\bpaintless dent repair technician\b|\bauto body prepper\b|\bautomotive (?:wheel|rim) repair technician\b",
            "mechanic",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_hvac_service_technician_explicit",
            r"\b(?:commercial\s+)?hvac service technician\b|\bhvac technician\b|\blead hvac service technician\b",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_diesel_technician_explicit",
            r"\b(?:experienced\s+)?diesel technician\b",
            "mechanic",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_telematics_installer_explicit",
            r"\btelematics installer\b",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_plumber_explicit",
            r"\b(?:lead\s+)?(?:install\s+)?plumber\b|\bjourneyman plumber\b",
            "field_technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_hvac_install_edge_v28",
            r"\bhvac lead installer\b|\bhvac install technician\b|\b(?:commercial\s+)?hvac installer\b|\bhvac apprentice\b",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_plumbing_install_service_edge_v28",
            r"\bplumbing install lead\b|\bplumbing install technician\b|\bplumbing service technician\b|\bplumbing apprentice\b",
            "field_technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_tool_trailer_technician_edge_v31",
            r"^tool trailer technician$",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_automotive_state_inspector_edge_v31",
            r"^automotive state inspector(?:\s*\(2nd shift\))?$|\bautomotive technician\b.*\bstate inspector\b",
            "mechanic",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_mechanical_electrical_tool_technician_explicit",
            r"\bmechanical technician\b|\belectrical technician\b|\btool technician\b|\belectro-mechanical technician\b",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_high_volume_technician_explicit",
            r"^field service technician$|^facilities technician$|^manufacturing technician$|^cultivation technician$|^assembly technician(?:\s+\(contract\))?$|^fire systems technician$|^auto airbrush technician$|^(?:experienced|senior)?\s*heavy body technician(?:\s+\(2nd shift\))?(?:\s+-\s+\d+(?:\s+\d+)?\s*bonus)?$|^master service technician(?:\s+-\s+\d+(?:\s+\d+)?\s*bonus)?$",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_auto_repair_detail_precision_v27",
            r"\bauto interior (?:and )?glass repair (?:tech|technician)\b|\bauto interior repair\s*-\s*glass repair (?:tech|technician)\b|\b(?:auto(?:motive)?\s+)?interior repair(?:\s*-\s*|\s+)(?:glass repair\s+)?(?:tech|technician)\b|\bpaintless dent repair (?:tech|technician)\b|\bpdr technician\b|\brim repair tech\b|\bautomotive wheel\s*-?\s*rim repair (?:tech|technician)\b|\bautomotive rim repair tech\b|\bauto rim repair tech\b|\b(?:automotive\s+)?rim repair technician\b|\b(?:auto(?:motive)?\s+)?rim repair\b|\bstellantis certified (?:master service )?technician\b|\b(?:auto\s?body|autobody)\b.*\b(?:inspector|prep(?:per| tech| technician)?|painter|estimator|apprentice|cosmetic(?:\s+inspector)?|line lead)\b",
            "mechanic",
            "skilled_trades",
            49,
        ),
        TitleRule(
            "trades_contract_field_service_technician_v27",
            r"^contract field service technician$",
            "technician",
            "skilled_trades",
            49,
        ),
        TitleRule("eng_devops", r"\bdevops engineer\b|\bdevops\b", "devops_engineer", "devops", 50),
        TitleRule("eng_sre", r"\bsite reliability engineer\b|\bsre\b", "site_reliability_engineer", "sre", 51),
        TitleRule("eng_ml", r"\bmachine learning engineer\b|\bml engineer\b", "ml_engineer", "machine_learning", 52),
        TitleRule("eng_data_scientist", r"\bdata scientist\b", "data_scientist", "data_science", 53),
        TitleRule("eng_security", r"\bsecurity engineer\b", "software_engineer", "software_engineering", 54),
        TitleRule("eng_python", r"\bpython engineer\b", "software_engineer", "software_engineering", 55),
        TitleRule("arch_solutions", r"\bsolutions architect\b", "solutions_architect", "architecture", 56),
        TitleRule(
            "it_support_engineer",
            r"\btechnical support engineer\b",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule(
            "it_support_engineer_core_safe_v2",
            r"^(?!.*\b(?:manager|director|head|chief)\b)(?!.*\b(?:customer|client|product|hardware|federal|designated|premium|spark|portworx|commodities|macro|trading|autonomy|curriculum)\b)(?:support engineer|senior support engineer|sr\.?\s*support engineer|lead support engineer|staff support engineer|associate support engineer|l2 support engineer|l3 support engineer|senior l2 support engineer|senior l3 support engineer|tier\s*[123]\s*support engineer|support engineer\s*\(tier\s*[123]\)|support engineer,\s*tier\s*[123]|application support engineer|cloud support engineer|software support engineer|systems?\s+support engineer|production support engineer|infrastructure support engineer|enterprise support engineer|database support engineer|platform support engineer|data center support engineer|tech support engineer|operations support engineer)(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "it_support_specialist",
            "it_operations",
            56,
        ),
        TitleRule(
            "it_support_engineer_it_context_v35",
            r"\b(?:senior\s+)?it support engineer(?:\s*(?:i|ii|iii))?\b|\bdesktop support engineer\b|\blinux desktop support engineer\b|\b(?:associate\s+)?linux support engineer\b|\bnetwork support engineer\b",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule(
            "it_support_specialist_it_context_v35",
            r"\b(?:senior\s+)?it support specialist(?:\s*(?:i|ii|iii))?\b|\bit support analyst\b|\bassociate it support analyst\b|\bit support technician(?:\s*(?:i|ii|iii))?\b|\bit support (?:team )?lead\b|\bexecutive it support\b",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule(
            "it_specialist_and_support_variants_v58",
            r"^associate it specialist$|^(?:[a-z0-9&+./-]+\s+)?application support specialist(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$|^windows platform support(?:\s*\((?:l1|l2|l3)\))?$",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule(
            "it_administrator_core_v54",
            r"^(?:senior|sr\.?|staff|principal|lead)?\s*it administrator(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule(
            "it_salesforce_administrator_core_v55",
            r"^(?:senior|sr\.?|staff|principal|lead|professional services)?\s*salesforce administrator(?:\s*(?:i|ii|iii|iv|v))?(?:\s*\([^)]*\))?(?:\s*[-,:].*)?$",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule(
            "it_product_support_specialist_core_v55",
            r"^(?:senior|associate)?\s*product support specialist(?:(?:\s+\w+(?:\s+\w+)*)|(?:\s*-\s*.*))?$",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule(
            "it_admin_variants_v58",
            r"^(?:aws\s+cloud|business applications|virtual platform)\s+administrator(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "it_support_specialist",
            "it_operations",
            57,
        ),
        TitleRule("admin_executive_assistant", r"\bexecutive assistant\b", "executive_assistant", "administrative_support", 58),
        TitleRule("design_product_designer", r"\bproduct designer\b|\bsenior product designer\b", "product_designer", "design", 59),
        TitleRule("eng_data_engineer", r"\bdata engineer\b", "data_engineer", "data_engineering", 60),
        TitleRule(
            "eng_tech_lead_core_product_v38",
            r"^tech lead\s+(?:android|web|mobile)\s+core product(?:\s*(?:&|and)\s*chrome extension)?(?:\s*-\s*.+)?$",
            "software_engineer",
            "software_engineering",
            60,
        ),
        TitleRule(
            "eng_software_development_engineer_variants_v34",
            r"\b(?:senior|staff|principal|lead|junior|sr\.?|jr\.?)?\s*(?:staff\s+)?software development engineer(?:\s+in test)?(?:\s*(?:i|ii|iii|iv|v|l\d+))?\b|\bsdet(?:[-\s]?[a-z0-9]+)?\b",
            "software_engineer",
            "software_engineering",
            60,
        ),
        TitleRule(
            "eng_mobile_engineer_android_ios_v46",
            r"\b(?:senior|staff|principal|lead|junior|jr\.?|associate|middle|sr\.?)?\s*(?:android|ios|mobile)\s+engineer\b|\bmobile\s+(?:android|ios)\s+engineer\b|\b(?:android|ios)\s+mobile engineer\b|\bengineer(?:\s*,|\s+)(?:android|ios|mobile)\b",
            "software_engineer",
            "software_engineering",
            60,
        ),
        TitleRule(
            "eng_fullstack_developer_core_safe_v5",
            r"\b(?:senior|sr\.?|staff|principal|lead|associate)?\s*(?:\.net\s+)?fullstack developer\b|\bfull stack developer\b",
            "software_engineer",
            "software_engineering",
            60,
        ),
        TitleRule(
            "arch_data_architect_core_safe_v3",
            r"^(?:senior|sr\.?|staff|principal|lead)?\s*data architect(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "solutions_architect",
            "architecture",
            60,
        ),
        TitleRule(
            "arch_enterprise_architect_core_safe_v5",
            r"\b(?:principal|senior|sr\.?|staff|lead|associate|it|ai|applications|salesforce|advisory services|technical advisory services)?\s*enterprise architect\b",
            "solutions_architect",
            "architecture",
            60,
        ),
        TitleRule(
            "arch_technical_architect_core_v54",
            r"^(?:senior|sr\.?|staff|principal|lead)?\s*technical architect(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "solutions_architect",
            "architecture",
            60,
        ),
        TitleRule(
            "arch_technical_architect_contextual_v55",
            r"^(?!.*\bmanager\b)(?:(?:senior|sr\.?|principal|lead)\s+)?(?:(?:ai|aws|servicenow|salesforce|boomi|life asia|field chief|professional services|senior professional services|information systems\s+open source)\s+)?technical architect(?:\s*(?:i|ii|iii|iv|v))?(?:(?:\s+\w+(?:\s+\w+)*)|(?:\s*-\s*.*))?$|^technical architect\s+ps$",
            "solutions_architect",
            "architecture",
            60,
        ),
        TitleRule(
            "eng_devsecops_engineer_core_safe_v3",
            r"^(?:senior|sr\.?|staff|principal|lead|chief)?\s*devsecops engineer(?:\s*(?:i|ii|iii|iv|v))?(?:\s*[-,:].*)?$",
            "devops_engineer",
            "devops",
            60,
        ),
        TitleRule("eng_software", r"\bsoftware engineer\b|\bsoftware developer\b|\bbackend engineer\b|\bfrontend engineer\b|\bfull[ -]?stack engineer\b", "software_engineer", "software_engineering", 61),
        TitleRule("data_analytics_engineer", r"\banalytics engineer\b", "analytics_engineer", "data_analytics", 62),
        TitleRule("data_analyst", r"\bdata analyst\b|\bbusiness intelligence analyst\b|\bbi analyst\b", "data_analyst", "data_analytics", 63),
        TitleRule(
            "data_sales_operations_analyst_safe_v7",
            r"\b(?:senior|sr\.?|principal|enterprise|apj|junior)?\s*sales operations analyst\b|\bsales operations analyst\b.*\b(?:renewals|insurance|amazon|latam)\b|\bsenior sales operation specialist\s*\(sales operations analyst\)",
            "data_analyst",
            "data_analytics",
            63,
        ),
        TitleRule("product_manager", r"\bproduct manager\b|\bproduct owner\b", "product_manager", "product_management", 60),
        TitleRule("program_tpm", r"\btechnical program manager\b|\btpm\b", "technical_program_manager", "program_management", 70),
        TitleRule("program_project_manager", r"\bproject manager\b|\bprogram manager\b", "project_manager", "program_management", 80),
        TitleRule("sales_account_exec", r"\baccount executive\b", "account_executive", "sales", 90),
        TitleRule(
            "sales_business_development_executive_v68",
            r"\b(?:federal\s+|iso\s+)?business development executive\b",
            "account_executive",
            "sales",
            95,
        ),
        TitleRule("sales_account_manager", r"\baccount manager\b|\bterritory account manager\b", "account_manager", "sales", 100),
        TitleRule("sales_bdr", r"\bbusiness development representative\b|\baccount development representative\b|\bbdr\b|\bsdr\b|\bsales development representative\b", "business_development_representative", "sales", 110),
        TitleRule(
            "csm_client_success_manager_core_safe_v3",
            r"\b(?:senior|sr\.?|staff|principal|lead|enterprise)?\s*client success manager\b",
            "customer_success_manager",
            "customer_success",
            119,
        ),
        TitleRule("csm", r"\bcustomer success manager\b|\bcustomer success\b", "customer_success_manager", "customer_success", 120),
        TitleRule("marketing_specialist", r"\bmarketing\b|\bgrowth marketing\b|\bsocial media manager\b", "marketing_specialist", "marketing", 130),
        TitleRule(
            "finance_fpna_core_v60",
            r"^(?:(?:senior|sr\.?|junior|jr\.?|lead|principal|manager|director|staff|associate)\s+|head(?:\s+of)?\s+)?(?:gtm\s+|field\s+|technology\s+)?fp&a(?:\s+(?:analyst|manager|specialist|lead|business partner))?(?:\s*(?:[-,:].*))?$",
            "financial_analyst",
            "finance",
            139,
        ),
        TitleRule(
            "finance_strategic_finance_core_v60",
            r"^(?:(?:senior|sr\.?|junior|jr\.?|lead|principal|manager|director|staff|associate)\s+|head(?:\s+of)?\s+)?strategic finance(?:\s+(?:analyst|manager|lead))?(?:\s*(?:[-,:].*))?$",
            "financial_analyst",
            "finance",
            139,
        ),
        TitleRule(
            "finance_quantitative_researcher_core_v61",
            r"^(?:senior|junior|experienced|summer intern 2026|intern|associate)?\s*(?:quantitative researcher|quant researcher)(?=.*\b(?:options|market making|equity|equities|commodities|trading|trading research|systematic|credit)\b)(?:\s+.*)?$",
            "quantitative_researcher",
            "finance",
            140,
        ),
        TitleRule("finance_analyst", r"\bfinancial analyst\b|\bfinance analyst\b|\btreasury analyst\b", "financial_analyst", "finance", 140),
        TitleRule(
            "finance_credit_analyst_core_v60",
            r"^(?:senior|sr\.?|junior|jr\.?|associate|supervisor|lead|principal)?\s*credit analyst(?:\s*(?:[-,:].*))?$",
            "credit_analyst",
            "finance",
            141,
        ),
        TitleRule("finance_accountant", r"\baccountant\b|\bcontroller\b|\bauditor\b", "accountant", "finance", 150),
        TitleRule("legal_counsel", r"\bcounsel\b|\battorney\b|\blegal\b", "legal_counsel", "legal", 160),
        TitleRule("recruiter", r"\brecruiter\b|\btalent acquisition\b", "technical_recruiter", "recruiting", 170),
        TitleRule("ops_specialist", r"\boperations specialist\b|\boperations coordinator\b|\bdelivery specialist\b", "operations_specialist", "operations", 180),
    ]
    return sorted(rules, key=lambda r: r.priority)
