sources:
  greenhouse:
    enabled: true
    boards:
    - speechify
    - equipmentsharecom
    - carvana
    - andurilindustries
    - spacex
    - launch2
    - blueskytelepsych
    - agency
    - databricks
    - capco
    - cloudflare
    - stripe
    - doordashusa
    - feverup
    - luminishealth
    - coupang
    - stone
    - aloyoga
    - okx
    - anthropic
    - samsara
    - datadog
    - axon
    - accenturefederalservices
    - purestorage
    - mongodb
    - horacemannagents
    - onemedical
    - nice
    - relativity
    - netskope
    - olsson
    - agoda
    - celonis
    - esri
    - adyen
    - doctolib
    - xai
    - rocketlab
    - toast
    - oscar
    - tegnainc
    - charliehealth
    - airbnb
    - axsometherapeutics
    - canonical
    - curaleaf
    - hubspotjobs
    - onrunning
    - sharkninjaoperatingllc
    - coinbase
    - coreweave
    - nebius
    - remotecom
    - point72
    - guidepostmontessori
    - cannondesign
    - quberesearchandtechnologies
    - prolific
    - klaviyo
    - formlabs
    - mediabrands
    - anaplan
    - appliedintuition
    - ebury
    - archer56
    - intercom
    - sofi
    - janestreet
    - rubrik
    - agibank
    - axiomtalentplatform
    - datavant2
    - elastic
    - apexcompanies
    - gleanwork
    - dept
    - gomotive
    - neoris
    - sonyinteractiveentertainmentglobal
    - aurorainnovation
    - connecteam
    - arcoeducacao
    - affirm
    - greenthumbindustries
    - fivetran
    - figma
    - sentinellabs
    - flexport
    - brex
    - lightspeedhq
    - fanduel
    - accelschools
    - gitlab
    - instacart
    - scopely
    - via
    - ixllearning
    - reddit
    - scaleai
    - five9
    - betsson
    - hitachidigitalservices
    - allcareers
    - dropbox
    - imc
    - lgelectronics
    - clickhouse
    - alphasense
    - lyft
    - inovalon
    - boxinc
    - natera
    - atwellgroup
    - grafanalabs
    - ibkr
    - precisionmedicinegroup
    - thenewyorktimes
    - asana
    - flywheeldigital
    - artefact
    - sezzle
    - 2k
    - aviationinstituteofmaintenance
    - robinhood
    - bethesdahealthgroup
    - braze
    - qualtrics
    - sondermind
    - appian
    - abnormalsecurity
    - boomilp
    - deepmind
    - capgeminideutschlandgmbh
    - fundraiseup
    - doitintl
    - astranis
    - jetbrains
    - powerdigitalmarketing
    - bondvet
    - drweng
    - orioninnovation
    - catonetworks
    - harnessinc
    - thetradedesk
    - tanium
    - artefactlinkedin
    - graphcore
    - payoneer
    - advancedtechnologyservices
    - knowbe4
    - shieldshealthsolutions
    - quince
    - focusfinancialpartners
    - abclegalservices
    - intersystems
    - postman
    - altentechnologyusa
    - pinterest
    - simtrabps
    - armissecurity
    - bitpanda
    - contentful
    - smartsheet
    - acornhealth
    - theknotworldwide
    - eucalyptus
    - springhealth66
    - takealotcom
    - asteralabs
    - metropolis
    - ripple
    - townsquaremedia
    - k2spacecorporation
    - motional
    - rebuildmanufacturing
    - justworks
    - redventures
    - barbaricum
    - betterhelp
    - mejuri
    - figureai
    - bitgo
    - taboola
    - gongio
    - thequalitygroupgmbh1
    - appier
    - metrostarsystems
    - modernanimal
    - ensono
    - flex
    - teads1
    - billiontoone
    - opswat
    - bloomreach
    - captiveaire
    - carta
    - cresta
    - moloco
    - freenow
    - harbingermotors
    - midihealth
    - opentable
    - aevexaerospace
    - gusto
    - merceradvisors
    - spauldingridge
    - strivehealth
    - flagshippioneeringinc
    - helsing
    - mozilla
    - nubank
    - pandadoc
    - dexisconsultinggroup
    - oliver
    - presidents
    - tekion
    - fireblocks
    - ionq
    - oura
    - rockstargames
    - tenstorrent
    - cottinghambutlerinsuranceservicesinc
    - dialpad
    - regionalspotonsales
    - chaosindustries
    - crunchyroll
    - headway
    - pomelocare
    - rdccareers
    - smartlyio
    - thequalitygroupgmbh2
    - hitachivantaracorporation
    - inmobi
    - godaddy
    - staffbase
    - addepar1
    - blackduck
    - cabify
    - careem
    - cloverhealth
    - c3iot
    - c6bank
    - dianahealth94
    - duolingo
    - neweratech
    - redis
    - cranialtechnologies
    - grammarly
    - paypay
    - redwoodmaterials
    - alarmcom
    - cerebrassystems
    - arcellx
    - discord
    - gympass
    - pharmacann
    - tripadvisor
    - lovable
    - airsculpt
    - billcom
    - clara
    - omguk
    - pingidentity
    - allinc
    - clutch
    - digicert
    - radiant
    - moveworks
    - similarweb
    - alpaca
    - coreone
    - isaraerospace
    - ivalua
    - linx
    - psiquantum
    - appdirect
    - blackbirdhealth
    - bridgebio
    - charlesriverassociates
    - chowbus
    - hudl
    - jumptrading
    - neuralink
    - trace3
    - bottomlinetechnologies
    - impact
    - planetlabs
    - chainguard
    - medier
    - myriad360
    - samsungsemiconductor
    - toogoodtogo
    - armada
    - catawiki
    - compasshealthcenter
    - cortica
    - sumologic
    - aspirehealthalliance
    - sothebys
    - twosixtechnologies
    - blockchain
    - earnin
    - opendoor
    - pairteam
    - recordedfuture
    - shinvestmentsllc
    - tatari
    - blankstreet
    - gatikaiinc
    - guidepointsecurity
    - hillel
    - newrelic
    - rapp
    - tenableinc
    - blackcanyonconsulting
    - galaxydigitalservices
    - acommerce
    - anchanto
    - axs
    - cribl
    - ethoslife
    - housecall
    - oklo
    - shift4
    - thoughtworks
    - akidolabs
    - genedx
    - groupon
    - lucidsoftware
    - rxvantage
    - engine
    - launchdarkly
    - blinkhealth
    - capitalrx
    - css
    - enviva
    - hs
    - northpointtechnology
    - altium
    - devrev
    - easygo
    - faire
    - kairospower
    - sollishealth
    - amplitude
    - apolloio
    - ayahealthcare
    - hightouch
    - landor
    - lighthouse
    - lightmatter
    - precisionaq
    - shipbobinc
    - abinbev
    - brandtechplus
    - brillapubliccharterschools
    - capitalontap
    - cialfo
    - collibra
    - fictiv
    - garnerhealth
    - monzo
    - onetrust
    - temporaltechnologies
    - angi
    - arlosolutionsllc
    - cityoffortworth
    - parloa
    - siei
    - skyscanner
    - webflow
    - 10xgenomics
    - beaconsoftware
    - carecom
    - corcepttherapeutics
    - gafg
    - seatgeek
    - sonderaustralia
    - blip-global
    - ridgeline
    - stokespacetechnologies
    - accordion
    - appsflyer
    - avetta
    - bamboohr17
    - beamtherapeutics
    - caronsale
    - chime
    - cision
    - convene
    - focuspartnerswealth
    - mercury
    - neuraflash
    - podium81
    - realtimeboardglobal
    - schonfeld
    - tipaltisolutions
    - agencywithin
    - arcesiumllc
    - arspharmaceuticalsoperationsinc
    - bancopan
    - beyondtrust
    - cultureamp
    - generalmatter
    - karbon
    - airtrunk
    - atlassand
    - checkr
    - firstglobalmanagementservicesinc
    - flohealth
    - forter
    - freeformfuturecorp
    - gofundme
    - manychat
    - orchard
    - sonypicturesimageworks
    - coherehealth
    - ebanx
    - instawork
    - sesai
    - squarespace
    - affinipay1
    - alliancedefendingfreedom
    - caylent
    - clear
    - fastly
    - formhealth
    - geniussports
    - iconcareers
    - neo4j
    - storable
    - airtable
    - amperesand
    - bandwidth
    - buildops
    - buyersedgeplatformrecruiting
    - gocardless
    - sweetgreen
    - tarsusrx
    - tecovas
    - thenuclearcompany
    - torq
    - allarahealth
    - dataiku
    - mavenclinic
    - pagerduty
    - propertyfinder
    - shipmonk
    - supplyhouse
    - a3c41b8b71eff8c4
    - la2028
    - operationscareers
    - prenuvo
    - securityscorecard
    - slice
    - wheely
    - acadiapharmaceuticals
    - altruist
    - butternutbox
    - doubleverify
    - hextechnologies
    - hyperiondev
    - jamf
    - levio
    - life360
    - madisonreedcolorbar
    - modulrfinance
    - pacificfusion
    - theeconomistgroup
    - breezeairways
    - humanagency
    - leagueinc
    - mrbeastyoutube
    - pathrobotics
    - platformscience
    - recursionpharmaceuticals
    - roofstock
    - topcompare
    - banyansoftware
    - daybreakhealth
    - echodynecorp
    - peloton
    - pleo
    - rithumliboard
    - skildai-careers
    - spire
    - togetherai
    - topsort
    - torcrobotics
    - wayve
    - alamarbiosciences
    - appodeal
    - auctane
    - bpcs
    - feedzai
    - givedirectly
    - golin
    - hotmartcareersbr
    - iherb
    content: true
